-- Disabled: image.nvim needs a kitty/ueberzug-capable terminal.
-- lazy.nvim requires every file under lua/plugins to return a spec table,
-- so return an empty one rather than nil while the config below is parked.
return {}

-- return {
--   "3rd/image.nvim",
--   lazy = false,
--   opts = {
--     backend = "kitty",
--     integrations = {
--       markdown = {
--         enabled = true,
--         resolve_image_path = function(document_path, image_path, fallback)
--           if require("obsidian.api").path_is_note(document_path) then
--             return require("obsidian.api").resolve_image_path(image_path)
--           end
--           return fallback(document_path, image_path)
--         end,
--       },
--     },
--   },
-- }
